* Solving Tower of Hanoi
** The purpose of this repository
   This repository contains model, view and controller classes for
   solving Tower of Hanoi.

** Installation in IDEA
   To install the application in IDEA, do the following:
   1. Clone the repository.
   2. Right click on class =TOHApp=.
   3. Select =Run TOHApp.main()=
   You are now able to make changes to the project and run it again.

** Alternative installation from command line
   1. Clone repository.
   2. Inside repo, run =ant= to build and run the app.
   
** GUI key bindings
   | key | action              |
   |-----+---------------------|
   | ~+~ | speed up animation  |
   | ~-~ | slow down animation |
   | ~q~ | quit                |

** Solving the tower of Hanoi
   Class =TOHApp= contains method
   #+begin_src java :exports code
     static void move (TowerOfHanoi toh, int numDiscs, Rod from, Rod to)
   #+end_src
   which you need to modify to solve the problems. The =main()= of
   this class calls method =move()= with correct parameters for
   solving the problem, that is, moving all discs from rod A to rod C.

   The version of =move()= in this repository is a feeble attempt to
   solve this problem, and you need to replace it with your own
   version. Still, the feeble version demonstrates all the external
   methods you need to use:
   - =enum Rod= contains static method
     #+begin_src java :exports code
       Rod third (Rod one, Rod another)
     #+end_src
     which returns the third rod given two rods.
   - =class TowerOfHanoi= contains method
     #+begin_src java :exports code
       move (Rod from, Rod to)
     #+end_src
     which moves top disc of rod =from= to rod =to=. This may throw an
     exception if the move breaks the rules of Tower of Hanoi, but
     this exception is caught by the program. Possible exceptions are
     printed into console.

** License
   Copyright (C) 2020 Jarmo Hurri

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
